platform :ios, '5.0'

pod 'AFNetworking', 	'~> 1.3.2'
pod 'SVPullToRefresh'
pod 'SVWebViewController'
pod 'Appirater'
pod 'FlurrySDK'
pod 'TDBadgedCell', '~> 2.3'
pod 'LastFm'
pod 'SVProgressHUD'
pod 'TestFlightSDK'
pod 'FXKeychain'
pod 'CKRefreshControl'
pod 'JSONModel'
pod 'ObjectiveSugar'
pod 'JASidePanels'
pod 'DTCoreText'
pod 'Audjustable', :head