platform :ios, '5.0'

pod 'AFNetworking', 	'~> 1.3.2'
pod 'SVWebViewController'
pod 'Appirater'
pod 'FlurrySDK'
pod 'TDBadgedCell', '~> 2.3'
pod 'LastFm'
pod 'SVProgressHUD'
pod 'TestFlightSDK'
pod 'FXKeychain'
pod 'CKRefreshControl'
pod 'ObjectiveSugar'
pod 'JASidePanels'
pod 'Underscore.m', '~> 0.2.1'

