platform :ios, '5.0'

pod 'AFNetworking', 	'~> 1.2.0'
pod 'SVPullToRefresh'
pod 'SVWebViewController'
pod 'Appirater'
pod 'FlurrySDK'
pod 'TDBadgedCell', '~> 2.3'
pod 'LastFm'
pod 'SVProgressHUD'
pod 'TestFlightSDK'
pod 'FXKeychain'
pod 'CKRefreshControl'
